name: generate animation

on:
  # Executa automaticamente a cada 24 horas
  schedule:
    - cron: "0 */24 * * *"

  # Permite executar manualmente o job a qualquer momento
  workflow_dispatch:

  # Executa a cada push no branch master
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Gera um jogo da cobrinha a partir do gráfico de contribuições do GitHub do usuário (<nome_do_usuário_do_github>), gera uma animação svg em <caminho_saida_svg>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: marceloteck
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Faz o push do conteúdo do <build_dir> para um branch
      # O conteúdo estará disponível em https://raw.githubusercontent.com/<usuário_do_github>/<repositório>/<target_branch>/<arquivo>, ou como página do GitHub
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
